spring:
  data:
    mongodb:
      uri: mongodb+srv://sushantsonkamble18457_db_user:VnuiFIN2vrLjzecf@cluster0.xqq2tis.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal
